app/Http/routes.php
<?php


/*
 * User Job Poster
 *
 * This is the User Portion of the site.
 * User can edit their properties.
 * But only their properties.
 */
Route::group([
    'middleware' => ['auth', 'role:super-admin|job-poster'],

], function() {

    Route::get('files/user/resumes/{systemFileName}','ResumeController@download');
    Route::get('files/user/cover-letter/{id}','UserCoverLetterController@download');

    Route::get('job-applications/{id}','JobApplicationController@show');
    Route::get('job/admin','JobPostingController@admin');
    Route::resource('job','JobPostingController',['except' => 'show']);

    Route::get('job/{id}/requirements',['as' => 'job.requirement.create', 'uses' => 'JobPostingController@createRequirements']);
    Route::post('job/{id}/requirements',['as' => 'job.requirement.store', 'uses' => 'JobPostingController@storeRequirements']);
    Route::get('job/{id}/requirements/edit',['as' => 'job.requirement.edit', 'uses' => 'JobPostingController@editRequirements']);
    Route::put('job/{id}/requirements',['as' => 'job.requirement.update', 'uses' => 'JobPostingController@updateRequirements']);

});

/*
 * Public
 *
 * This is the Public Portion of the site.
 */
Route::get('/', 'StaticController@home');
Route::get('/privacy', 'StaticController@privacyPolicy');
Route::get('/terms', 'StaticController@termsOfUse');
Route::get('/search',['as' => 'job-search', 'uses' => 'JobSearchController@index']);
Route::get('/data/city-state', 'PositionController@ajaxGetCityState');
Route::auth();
Route::get('job/{id}',['as' => 'job.show', 'uses' => 'JobPostingController@show']);

/*
 * Movology Test
 */
Route::get("/movology/source", "MovologyController@source");
Route::get("/movology",'MovologyController@index');
Route::post("/movology",'MovologyController@index');

/*
 * Admin
 *
 * This is the Admin Portion of the site.
 * Access is restricted here.
 * admin only.
 */

Route::group([
    'middleware' => ['auth', 'role:admin|super-admin'],
    'prefix'     => 'admin'
], function() {

    Route::post('ajax/job-publish','JobPostingController@publish');
    Route::post('ajax/job-unpublish','JobPostingController@unpublish');

    Route::get('user/roles','RoleController@index');
    Route::resource('user','UserController');
    Route::resource('roles','RoleController');

});

/*
 * Ajax
 *
 * This is the Ajax Portion of the site.
 * Ajax calls are routed here.
 */
Route::group([
    'middleware' => 'auth',
    'prefix'     => 'ajax'
], function() {


    Route::post('job/apply','JobApplicationController@ajaxApply');
    Route::put('user/cover-letters/{cover_letters}','UserCoverLetterController@ajaxUpdate');
    Route::delete('user/cover-letters/{cover_letters}','UserCoverLetterController@ajaxDestroy');

    Route::resource('user/job-status','UserJobStatusController', ['only' => 'store','show','update','destroy']);
});

/*
 * User (Any Registered User)
 *
 * This is the User Portion of the site.
 * User can edit their properties.
 * But only their properties.
 */
Route::group([
    'middleware' => 'auth',
    ], function() {

    Route::get('apply/{id}','JobApplicationController@apply');

    Route::get('user/profile','UserController@profile');
    Route::post('user/profile','UserController@profileUpdate');

    Route::resource('user/resumes','ResumeController');
    Route::resource('user/cover-letters','UserCoverLetterController');

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use EntrustUserTrait;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getCoverLetterArray()
    {
        $coverArray = [ '0' => 'No Cover Letter'];

        foreach($this->coverLetters as $cover) {
            $coverArray[$cover->id] = $cover->name;
        }

        return $coverArray;
    }

    public function getDefaultCoverLetter()
    {
        foreach($this->coverLetters as $cover) {
            if($cover->default == 1) {
                return $cover->id;
            }
        }

        return false;
    }

    public function getResumesArray()
    {
        $resumeArray = [];

        foreach($this->resumes as $resume) {
            $resumeArray[$resume->id] = $resume->name;
        }

        if(count($resumeArray) == 0) {
            $resumeArray['0'] = "No Resumes.";
        }

        return $resumeArray;
    }

    public function getDefaultResume()
    {
        foreach($this->resumes as $resume) {
            if($resume->default == 1) {
                return $resume->id;
            }
        }

        return false;
    }

    public function userContact()
    {
        return $this->hasOne(UserContact::class);
    }

    public function resumes()
    {
        return $this->hasMany(UserResume::class);
    }

    public function coverLetters()
    {
        return $this->hasMany(UserCoverLetter::class);
    }

    public function jobStatuses()
    {
        return $this->hasMany(UserJobStatus::class);
    }

    public function jobPostings()
    {
        return $this->hasMany(JobPosting::class);
    }

    public function jobApplications()
    {
        return $this->hasMany(JobApplication::class);
    }

    public function jobView()
    {
        return $this->hasMany(JobView::class);
    }

    public function UserJobPostingStat()
    {
        return $this->hasOne(UserJobPostingStat::class, "user_id");
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Auth\Role;
use App\Models\Auth\Permission;
use DB;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = Role::orderBy('id', 'DESC')->paginate(5);
        return view('pages.admin.user.roles.index', compact('roles'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permission = Permission::get();
        return view('pages.admin.user.roles.create', compact('permission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'display_name' => 'required',
            'description' => 'required',
            'permission' => 'required',
        ]);

        $role = new Role();
        $role->name = $request->input('name');
        $role->display_name = $request->input('display_name');
        $role->description = $request->input('description');
        $role->save();

        foreach ($request->input('permission') as $key => $value) {
            $role->attachPermission($value);
        }

        return redirect()->route('admin.roles.index')
            ->with('success', 'Role created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("permission_role", "permission_role.permission_id", "=", "permissions.id")
            ->where("permission_role.role_id", $id)
            ->get();

        return view('pages.admin.user.roles.show', compact('role', 'rolePermissions'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        $permission = Permission::get();
        $rolePermissions = DB::table("permission_role")->where("permission_role.role_id", $id)
            ->lists('permission_role.permission_id', 'permission_role.permission_id');

        return view('pages.admin.user.roles.edit', compact('role', 'permission', 'rolePermissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'display_name' => 'required',
            'description' => 'required',
            'permission' => 'required',
        ]);

        $role = Role::find($id);
        $role->display_name = $request->input('display_name');
        $role->description = $request->input('description');
        $role->save();

        DB::table("permission_role")->where("permission_role.role_id", $id)
            ->delete();

        foreach ($request->input('permission') as $key => $value) {
            $role->attachPermission($value);
        }

        return redirect()->route('admin.roles.index')
            ->with('success', 'Role updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table("roles")->where('id', $id)->delete();
        return redirect()->route('admin.roles.index')
            ->with('success', 'Role deleted successfully');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\UserContact;
use App\Models\Auth\Role;
use Illuminate\Http\Request;
use Auth;

use App\Http\Requests;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = User::orderBy('id','DESC')->paginate(5);
        return view('pages.admin.user.index',compact('data'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::lists('display_name','id');
        return view('pages.admin.user.create',compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email|unique:users,email',
            'password' => 'required|same:confirm-password',
            'roles' => 'required'
        ]);

        $input = $request->all();
        $input['password'] = bcrypt($input['password']);

        $user = User::create($input);
        foreach ($request->input('roles') as $key => $value) {
            $user->attachRole($value);
        }

        return redirect()->route('admin.user.index')
            ->with('success','User created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('pages.admin.user.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::lists('display_name','id');
        $userRole = $user->roles->lists('id','id')->toArray();

        return view('pages.admin.user.edit',compact('user','roles','userRole'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'email' => 'required|email|unique:users,email,'.$id,
            'password' => 'same:confirm-password',
            'roles' => 'required'
        ]);

        $input = $request->all();
        if(!empty($input['password'])){
            $input['password'] = Hash::make($input['password']);
        }else{
            $input = array_except($input,array('password'));
        }

        $user = User::find($id);
        $user->update($input);
        $user->detachRoles();


        foreach ($request->input('roles') as $key => $value) {
            $user->attachRole($value);
        }

        return redirect()->route('admin.user.index')
            ->with('success','User updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('admin.user.index')
            ->with('success','User deleted successfully');
    }

    public function profile()
    {
        if(!$contact = Auth::user()->userContact) {
            $contact = new UserContact();
        }

        return view('pages.user.profile',['contact' => $contact]);
    }

    public function profileUpdate(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email|unique:users,email,' . Auth::user()->id
        ]);

        if(!$contact = Auth::user()->userContact) {
            $contact = new UserContact();
        }

        $contact->address  = $request->input('address');
        $contact->address2 = $request->input('address2');
        $contact->city     = $request->input('city');
        $contact->state    = $request->input('state');
        $contact->zip      = $request->input('zip');
        $contact->phone    = $request->input('phone');
        $contact->user_id  = Auth::user()->id;
        $success = $contact->save();

        if($success) {
            Auth::user()->first_name = $request->input('first_name');
            Auth::user()->last_name  = $request->input('last_name');
            Auth::user()->email      = $request->input('email');
            $success = Auth::user()->save();
        }

        $request->session()->flash('success', 'Profile Updated.');

        return view('pages.user.profile', ['contact' => $contact]);
    }
}

resources/views/pages/admin/user/roles/_form.blade.php
<div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-12">
        <div class="form-group">
            <strong>Name:</strong>
            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
        </div>
        <div class="form-group">
            <strong>Display Name:</strong>
            {!! Form::text('display_name', null, array('placeholder' => 'Display Name','class' => 'form-control')) !!}
        </div>
        <div class="form-group">
            <strong>Description:</strong>
            {!! Form::textarea('description', null, array('placeholder' => 'Description','class' => 'form-control','style'=>'height:100px')) !!}
        </div>
        <div class="form-group">
            <strong>Permission:</strong>
            <br/>
            @foreach($permission as $value)
                <label>{{ Form::checkbox('permission[]', $value->id, isset($rolePermissions) && in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }}
                    {{ $value->display_name }}</label>
                <br/>
            @endforeach
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</div>

resources/views/pages/admin/user/roles/create.blade.php
@extends('layouts.admin')

@section('title', 'User Roles Index')
@section('metaDescription', 'User Roles Page')

@section('admin-content')
    <div class="panel">
        <div class="panel-heading">
            <div class="row">
                <div class="pull-left">
                    <h1>Create New Role</h1>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('admin.roles.index') }}"> Back</a>
                </div>
            </div>
        </div>
        <div class="panel-body">
            {!! Form::open(array('route' => 'roles.store','method'=>'POST')) !!}
            @include('pages.admin.user.roles._form')
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/pages/admin/user/roles/edit.blade.php
@extends('layouts.admin')

@section('title', 'User Roles Index')
@section('metaDescription', 'User Roles Page')

@section('admin-content')
    <div class="panel">
        <div class="panel-heading">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h1>Create New Role</h1>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('admin.roles.index') }}"> Back</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-body">
            {!! Form::model($role, array('route' => ['admin.roles.update', $role->id],'method'=>'PATCH')) !!}
            @include('pages.admin.user.roles._form')
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/pages/admin/user/roles/index.blade.php
@extends('layouts.admin')

@section('title', 'User Roles Index')
@section('metaDescription', 'User Roles Page')

@section('admin-content')
    <div class="panel">
        <div class="panel-heading">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h1>Role Management</h1>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-success" href="{{ route('admin.roles.create') }}"> Create New Role</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th width="280px">Action</th>
                    </tr>
                </thead>
                <tbody>
                @foreach ($roles as $key => $role)
                    <tr>
                        <td>{{ ++$i }}</td>
                        <td>{{ $role->display_name }}</td>
                        <td>{{ $role->description }}</td>
                        <td>
                            <a class="btn btn-info" href="{{ route('admin.roles.show',$role->id) }}">Show</a>
                            <a class="btn btn-warning" href="{{ route('admin.roles.edit',$role->id) }}">Edit</a>
                            {!! Form::open(['method' => 'DELETE','route' => ['admin.roles.destroy', $role->id],'style'=>'display:inline']) !!}
                            {!! Form::submit('Delete', ['class' => 'btn btn-primary']) !!}
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {!! $roles->render() !!}
        </div>
    </div>
@endsection

resources/views/pages/admin/user/roles/show.blade.php
@extends('layouts.admin')

@section('title', 'User Roles Index')
@section('metaDescription', 'User Roles Page')

@section('admin-content')
    <div class="panel">
        <div class="panel-heading">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h1>Show Role</h1>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('admin.roles.index') }}"> Back</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Name:</strong>
                        {{ $role->display_name }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Description:</strong>
                        {{ $role->description }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Permissions:</strong>
                        @if(!empty($rolePermissions))
                            @foreach($rolePermissions as $v)
                                <label class="label label-success">{{ $v->display_name }}</label>
                            @endforeach
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection