app/Http/routes.php
<?php


/*
 * User Job Poster
 *
 * This is the User Portion of the site.
 * User can edit their properties.
 * But only their properties.
 */
Route::group([
    'middleware' => ['auth', 'role:super-admin|job-poster'],

], function() {

    Route::get('files/user/resumes/{systemFileName}','ResumeController@download');
    Route::get('files/user/cover-letter/{id}','UserCoverLetterController@download');

    Route::get('job-applications/{id}','JobApplicationController@show');
    Route::get('job/admin','JobPostingController@admin');
    Route::resource('job','JobPostingController',['except' => 'show']);

    Route::get('job/{id}/requirements',['as' => 'job.requirement.create', 'uses' => 'JobPostingController@createRequirements']);
    Route::post('job/{id}/requirements',['as' => 'job.requirement.store', 'uses' => 'JobPostingController@storeRequirements']);
    Route::get('job/{id}/requirements/edit',['as' => 'job.requirement.edit', 'uses' => 'JobPostingController@editRequirements']);
    Route::put('job/{id}/requirements',['as' => 'job.requirement.update', 'uses' => 'JobPostingController@updateRequirements']);

});

/*
 * Public
 *
 * This is the Public Portion of the site.
 */
Route::get('/', 'StaticController@home');
Route::get('/privacy', 'StaticController@privacyPolicy');
Route::get('/terms', 'StaticController@termsOfUse');
Route::get('/search',['as' => 'job-search', 'uses' => 'JobSearchController@index']);
Route::get('/data/city-state', 'PositionController@ajaxGetCityState');
Route::auth();
Route::get('job/{id}',['as' => 'job.show', 'uses' => 'JobPostingController@show']);

/*
 * Movology Test
 */
Route::get("/movology/source", "MovologyController@source");
Route::get("/movology",'MovologyController@index');
Route::post("/movology",'MovologyController@index');

/*
 * Admin
 *
 * This is the Admin Portion of the site.
 * Access is restricted here.
 * admin only.
 */

Route::group([
    'middleware' => ['auth', 'role:admin|super-admin'],
    'prefix'     => 'admin'
], function() {

    Route::post('ajax/job-publish','JobPostingController@publish');
    Route::post('ajax/job-unpublish','JobPostingController@unpublish');

    Route::get('user/roles','RoleController@index');
    Route::resource('user','UserController');
    Route::resource('roles','RoleController');

});

/*
 * Ajax
 *
 * This is the Ajax Portion of the site.
 * Ajax calls are routed here.
 */
Route::group([
    'middleware' => 'auth',
    'prefix'     => 'ajax'
], function() {


    Route::post('job/apply','JobApplicationController@ajaxApply');
    Route::put('user/cover-letters/{cover_letters}','UserCoverLetterController@ajaxUpdate');
    Route::delete('user/cover-letters/{cover_letters}','UserCoverLetterController@ajaxDestroy');

    Route::resource('user/job-status','UserJobStatusController', ['only' => 'store','show','update','destroy']);
});

/*
 * User (Any Registered User)
 *
 * This is the User Portion of the site.
 * User can edit their properties.
 * But only their properties.
 */
Route::group([
    'middleware' => 'auth',
    ], function() {

    Route::get('apply/{id}','JobApplicationController@apply');

    Route::get('user/profile','UserController@profile');
    Route::post('user/profile','UserController@profileUpdate');

    Route::resource('user/resumes','ResumeController');
    Route::resource('user/cover-letters','UserCoverLetterController');

});

app/Models/JobPosting.php
<?php

namespace App\Models;

use App\Blip\GeoPosition;
use Illuminate\Database\Eloquent\Model;

class JobPosting extends Model
{
    use GeoPosition;

    protected $geofields = array('location_latlon');

    public function getTargetAttribute()
    {
        if($this->job_source_id == JobSource::where('name','BlipJobs')->first()->id) {
            return "_self";
        } else {
            return "_blank";
        }
    }

    public function getUrlAttribute($value)
    {
        if($this->job_source_id == JobSource::where('name','BlipJobs')->first()->id) {
            return "/job/" . $this->id;
        } else {
            return $value;
        }
    }

    public function getSnippet()
    {
        return substr(strip_tags($this->description),0,200)  . '...';
    }

    public function setJobSourceKey()
    {
        $this->job_source_key = sha1($this->company . $this->position .
            $this->location_city . $this->location_state );
    }


    public function jobApplications()
    {
        return $this->hasMany(JobApplication::class);
    }

    public function jobPositions()
    {
        return $this->belongsToMany('App\Models\JobPosition', 'job_position_job_posting');
    }

    public function jobPostingExperienceReq()
    {
        return $this->hasMany('App\Models\JobPostingExperienceReq');
    }

    public function jobPostingLanguageReq()
    {
        return $this->hasMany('App\Models\JobPostingLanguageReq');
    }

    public function jobPostingLicenseReq()
    {
        return $this->hasMany('App\Models\JobPostingLicenseReq');
    }

    public function jobSource()
    {
        return $this->belongsTo('App\Models\JobSource');
    }

    public function jobView()
    {
        return $this->hasMany(JobView::class);
    }

    public function jobViewStat()
    {
        return $this->hasOne(JobViewStat::class, 'job_posting_id');
    }

    public function jobApplicationStat()
    {
        return $this->hasOne(JobApplicationStat::class, 'job_posting_id');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

}

resources/views/pages/search/_sidebar.blade.php
<div class="col-sm-3 col-lg-2 sidebar job-summary-sidebar">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h2>Search Filters</h2>
        </div>
        <div class="panel-body">
            {!! Form::open(array('route' => 'job-search','method'=>'GET')) !!}
            <div class="form-group-sm">
                <label class="control-label">Job Search:</label>
                {!! Form::text('q', $input['q'], array('placeholder' => '','class' => 'form-control input-sm')) !!}
            </div>
            <div class="form-group-sm">
                <label class="control-label">Location:</label>
                {!! Form::text('l', $input['l'], array('placeholder' => '','class' => 'form-control input-sm', 'id' => 'location')) !!}
            </div>
            <div class="form-group-sm">
                <label class="control-label">Radius:</label>
                {!! Form::select('r',[
                '0'   => 'Exact Location',
                '5'   => '5 miles',
                '10'  => '10 miles',
                '15'  => '15 miles',
                '25'  => '25 miles',
                '50'  => '50 miles',
                '100' => '100 miles'], isset($input['r']) ? $input['r'] : '5' , array('class' => 'form-control ')) !!}
            </div>
            <div class="form-group-sm">
                <label class="control-label">Job Type:</label>
                {!! Form::select('jt',[
                null         => 'All',
                'temporary'  => 'Temporary',
                'parttime'   => 'Part Time',
                'fulltime'   => 'Full Time',
                'internship' => 'Internship',
                'contract'   => 'Contract',
                'commission' => 'Commission'], isset($input['jt']) ? $input['jt'] : null, array('class' => 'form-control ')) !!}
            </div>
            <div class="form-group-sm">
                <label class="control-label">Posting Age:</label>
                {!! Form::select('fromage',[
                'any'    => 'Anytime',
                '15'     => 'within 15 days',
                '7'      => 'within 7 days',
                '3'      => 'within 3 days',
                '1'      => 'since yesterday'], isset($input['fromage']) ? $input['fromage'] : 'any', array('class' => 'form-control ')) !!}
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center submit">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/pages/search/list.blade.php
@extends('layouts.default')

@section('title', 'Search Results ' . $input['q'] . " " . $input['l'] )
@section('metaDescription', 'Blip Jobs is a job search and posting website.  The Site is here to help job seekers to find
employment.  Employers may also use the site to post jobs.  It uses many other sites to aggregate job data.  It also has
functionality to assist users in organizing their job search.')

@section('content')

<div class="row">
    @include('pages.search._sidebar')
    <div class="col-sm-7 col-lg-8">
        @include('partials.messages')
        <div class="panel panel-default job-summary-panel">
            <div class="panel-heading">

            @if($jobs->count() > 0)
                <div class="row">
                    <div class="col-xs-4"><h1>Results</h1></div>
                    <div class="col-xs-8">
                        <span class="pull-right result-count">
                            {{($jobs->currentPage()-1) * $jobs->perPage() + 1}} - {{$jobs->lastPage() == $jobs->currentPage() ? $jobs->total() : $jobs->currentPage() * $jobs->perPage()}} of {{ $jobs->total() }}
                        </span>
                    </div>
                </div>

                @else
                    <h1>No Results</h1>
                @endif
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
                        @foreach($jobs as $job)
                            <div class="job-summary">
                                <div class="row">
                                    @if(Auth::check())
                                    <div class="col-xs-9">
                                    @else
                                    <div class="col-xs-12">
                                    @endif
                                        <h2><a class="job-link" href="{{ $job->url }}" target="{{ $job->target }}" data-status="viewed" data-id="{{ $job->id }}">{{ ucwords(strtolower($job->position)) }}</a></h2>
                                    </div>
                                    @if(Auth::check())
                                    <div class="col-xs-3 dropdown job-status">
                                        <div class="pull-right">
                                            <button id="status-{{ $job->id }}" class="job-status-btn btn btn-sm {{ isset($job->statusStyle) ? $job->statusStyle : "btn-primary" }} dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <span class="job-status-current">{{ isset($job->status) ? $job->status : "New" }}</span>
                                                <span class="caret"></span>
                                            </button>
                                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                                <li><a class="job-link" href="#" data-status="applied" data-id="{{ $job->id }}">Applied</a></li>
                                                <li><a class="job-link" href="#" data-status="interview" data-id="{{ $job->id }}">Interviewing</a></li>
                                                <li><a class="job-link" href="#" data-status="offer" data-id="{{ $job->id }}">Job Offer</a></li>
                                                <li><a class="job-link" href="#" data-status="not-interested" data-id="{{ $job->id }}">Not Interested</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    @endif
                                </div>

                                <div class="row">
                                    <div class="col-xs-12">
                                        <p><b>{{ $job->company ? ucwords(strtolower($job->company)) : "Undisclosed" }} - {{ ucwords(strtolower($job->location_city)) . ", " . $job->location_state }}</b></p>
                                        <p>{{ $job->getSnippet() }}</p>
                                        <time>{{ $job->posted_at->format("F j") }}</time><br/>
                                    </div>
                                </div>
                            </div>
                        @endforeach

                        @if($jobs->count() > 0)
                            <div class="text-center">
                                {{ $jobs->appends($input)->links() }}
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection