app/Http/routes.php
<?php


/*
 * User Job Poster
 *
 * This is the User Portion of the site.
 * User can edit their properties.
 * But only their properties.
 */
Route::group([
    'middleware' => ['auth', 'role:super-admin|job-poster'],

], function() {

    Route::get('files/user/resumes/{systemFileName}','ResumeController@download');
    Route::get('files/user/cover-letter/{id}','UserCoverLetterController@download');

    Route::get('job-applications/{id}','JobApplicationController@show');
    Route::get('job/admin','JobPostingController@admin');
    Route::resource('job','JobPostingController',['except' => 'show']);

    Route::get('job/{id}/requirements',['as' => 'job.requirement.create', 'uses' => 'JobPostingController@createRequirements']);
    Route::post('job/{id}/requirements',['as' => 'job.requirement.store', 'uses' => 'JobPostingController@storeRequirements']);
    Route::get('job/{id}/requirements/edit',['as' => 'job.requirement.edit', 'uses' => 'JobPostingController@editRequirements']);
    Route::put('job/{id}/requirements',['as' => 'job.requirement.update', 'uses' => 'JobPostingController@updateRequirements']);

});

/*
 * Public
 *
 * This is the Public Portion of the site.
 */
Route::get('/', 'StaticController@home');
Route::get('/privacy', 'StaticController@privacyPolicy');
Route::get('/terms', 'StaticController@termsOfUse');
Route::get('/search',['as' => 'job-search', 'uses' => 'JobSearchController@index']);
Route::get('/data/city-state', 'PositionController@ajaxGetCityState');
Route::auth();
Route::get('job/{id}',['as' => 'job.show', 'uses' => 'JobPostingController@show']);

/*
 * Movology Test
 */
Route::get("/movology/source", "MovologyController@source");
Route::get("/movology",'MovologyController@index');
Route::post("/movology",'MovologyController@index');

/*
 * Admin
 *
 * This is the Admin Portion of the site.
 * Access is restricted here.
 * admin only.
 */

Route::group([
    'middleware' => ['auth', 'role:admin|super-admin'],
    'prefix'     => 'admin'
], function() {

    Route::post('ajax/job-publish','JobPostingController@publish');
    Route::post('ajax/job-unpublish','JobPostingController@unpublish');

    Route::get('user/roles','RoleController@index');
    Route::resource('user','UserController');
    Route::resource('roles','RoleController');

});

/*
 * Ajax
 *
 * This is the Ajax Portion of the site.
 * Ajax calls are routed here.
 */
Route::group([
    'middleware' => 'auth',
    'prefix'     => 'ajax'
], function() {


    Route::post('job/apply','JobApplicationController@ajaxApply');
    Route::put('user/cover-letters/{cover_letters}','UserCoverLetterController@ajaxUpdate');
    Route::delete('user/cover-letters/{cover_letters}','UserCoverLetterController@ajaxDestroy');

    Route::resource('user/job-status','UserJobStatusController', ['only' => 'store','show','update','destroy']);
});

/*
 * User (Any Registered User)
 *
 * This is the User Portion of the site.
 * User can edit their properties.
 * But only their properties.
 */
Route::group([
    'middleware' => 'auth',
    ], function() {

    Route::get('apply/{id}','JobApplicationController@apply');

    Route::get('user/profile','UserController@profile');
    Route::post('user/profile','UserController@profileUpdate');

    Route::resource('user/resumes','ResumeController');
    Route::resource('user/cover-letters','UserCoverLetterController');

});

app/Models/JobView.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class JobView extends Model
{
    protected $fillable = ['job_posting_id', 'user_id'];

    public function jobPostings()
    {
        return $this->belongsTo(JobPosting::class);
    }

    public function users()
    {
        return $this->belongsTo(User::class);
    }
}

resources/views/pages/job/_form.blade.php
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script type="text/javascript">
    tinymce.init({
        selector: '#job-post-textarea'
    });
</script>


<div class="row">
    <div class="col-lg-6 col-sm-12">
        <div class="form-group">
            <strong>Company:</strong>
            {!! Form::text('company', null, array('placeholder' => '','class' => 'form-control', 'tabindex' => 1, 'autofocus')) !!}
        </div>
    </div>
    <div class="col-lg-6 col-sm-12">
        <strong>Position:</strong>
        <div class="row">
            <div class="col-xs-8">
                <div class="form-group">
                    {!! Form::text('position', null, array('placeholder' => '','class' => 'form-control', 'tabindex' => 2)) !!}
                </div>
            </div>
            <div class="col-xs-4">
                <div class="form-group">
                    {!! Form::select('position_type', [
                    'full-time' => 'Full Time',
                    'part-time' => 'Part Time',
                    'temp'      => 'Temporary',
                    'contract'  => 'Contract',
                    'intern'    => 'Commission'
                    ],isset($jobPosting) ? $jobPosting->jobPositions->first()->blip_name : null, array('class' => 'form-control', 'tabindex' => 3)) !!}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <strong>Contact:</strong>
        <div class="form-group">
            {!! Form::text('contact', null, array('placeholder' => 'Email','class' => 'form-control', 'tabindex' => 4)) !!}
        </div>
    </div>
    <div class="col-lg-6">
        <strong>Location:</strong>
        <div class="row">

            <div class="col-lg-6 col-sm-12">
                <div class="form-group">
                    {!! Form::text('location_city', null, array('placeholder' => 'City','class' => 'form-control', 'tabindex' => 5)) !!}
                </div>
            </div>
            <div class="col-lg-3 col-sm-12">
                <div class="form-group">
                    {!! Form::select('location_state', $states ,null, array('class' => 'form-control', 'tabindex' => 6)) !!}
                </div>
            </div>
            <div class="col-lg-3 col-sm-12">
                <div class="form-group">
                    {!! Form::text('location_zipcode', null, array('placeholder' => 'Zip Code','class' => 'form-control', 'tabindex' => 7)) !!}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6 col-sm-12">
        <strong>Compensation: (optional)</strong>
        <div class="row">
            <div class="col-xs-8">
                <div class="form-group">
                    {!! Form::text('salary', null, array('placeholder' => '','class' => 'form-control', 'tabindex' => 8)) !!}
                </div>
            </div>
            <div class="col-xs-4">
                <div class="form-group">
                    {!! Form::select('salary_per', [
                    'hour'  => 'Per Hour',
                    'day'   => 'Per Day',
                    'month' => 'Per Month',
                    'year'  => 'Per Year',
                    ],null, array('class' => 'form-control', 'tabindex' => 9)) !!}
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-sm-12">
        <div class="form-group">
            <strong>Education Requirement:</strong>
            {!! Form::select('education', [
            'none'        => 'None',
            'high-school' => 'High School',
            'bachelor'    => 'Bachelors',
            'master'      => 'Masters',
            'doctorate'   => 'Doctorate',
            ],null, array('class' => 'form-control', 'tabindex' => 10)) !!}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="form-group">
            <strong>Job Description:</strong>
            {!! Form::textarea('description', null, array('size' => '50x20','id' => 'job-post-textarea','class' => 'form-control')) !!}
        </div>
    </div>
</div>

resources/views/pages/job/_table.blade.php
<table class="table table-sm job-posting-table">
    <thead>
    <tr>
        <th>Company</th>
        <th>Title</th>
        <th class="hidden-sm hidden-xs">Location</th>
        <th class="hidden-md hidden-sm hidden-xs">Created</th>
        <th class="hidden-md hidden-sm hidden-xs">Published</th>
        <th class="hidden-xs">Views</th>
        <th class="hidden-xs">Applications</th>
        <th>Controls</th>
    </tr>
    </thead>
    <tbody>
    @foreach($jobPostings as $jobPosting)
        <tr id="job-posting-{{ $jobPosting->id }}" class="job-posting-row">
            <td>{{ substr($jobPosting->company,0,20) }}</td>
            <td>{{ substr($jobPosting->position,0,20) }}</td>
            <td class="hidden-sm hidden-xs">{{ $jobPosting->location_city . ", " . $jobPosting->location_state }}</td>
            <td class="hidden-md hidden-sm hidden-xs">{{ $jobPosting->created_at }}</td>
            <td class="job-posting-posted">{{ $jobPosting->posted ? 'Yes' : 'No' }}</td>
            <td class="hidden-xs">{{ $jobPosting->view_count ? $jobPosting->view_count : 0 }}</td>
            <td class="hidden-xs">
                @if($jobPosting->application_count)
                    <a href="/job-applications/{{ $jobPosting->id }}">{{ $jobPosting->application_count }}</a>
                @else
                    0
                @endif
            </td>
            <td>
                <a class="btn btn-info" href="{{ route('job.show', $jobPosting->id) }}">Show</a>
                @role('job-poster')
                <a class="btn btn-warning" href="{{ route('job.edit', $jobPosting->id) }}">Edit</a>
                @endif
                @role('super-admin')
                @if($jobPosting->posted)
                    <button class="btn btn-warning job-posting-unpublish" value="{{ $jobPosting->id }}">Unpub</button>
                @else
                    <button class="btn btn-success job-posting-publish" value="{{ $jobPosting->id }}">Pub</button>
                @endif
                @endrole
                <button class="btn btn-primary job-posting-confirm-delete" value="{{ $jobPosting->id }}" data-job-posting-name="{{ $jobPosting->company }} - {{ $jobPosting->position }}">Delete</button>
            </td>
        </tr>
    @endforeach
    </tbody>
    <tfoot>
    <tr>
        <td colspan="8"><a href="/job/create">Add Job Post</a></td>
    </tr>
    </tfoot>
</table>
@if($jobPostings->count() > 0)
    <div class="text-center">
        {{ $jobPostings->appends(isset($input)?$input:'')->links() }}
    </div>
@endif

@section('confirmClickClass','job-posting-delete')
@section('confirmHeader', 'Delete Job Posting')
@section('confirmBody')
    <p>
        Are you sure you want to delete the Job Posting, <strong>"<span id="confirm-job-posting-name"></span></strong>"?
    </p>
@endsection

@include('partials.modal.confirmDelete')

resources/views/pages/job/admin.blade.php
@extends('layouts.default')

@section('title', 'Home Page')
@section('metaDescription', 'Blip Jobs is a job search and posting website.  The Site is here to help job seekers to find
employment.  Employers may also use the site to post jobs.  It uses many other sites to aggregate job data.  It also has
functionality to assist users in organizing their job search.')
@section('siteBackground', 'home-background-logo')

@section('content')

<div class="row">
    @include('partials.posterSidebar')
    <div class="col-lg-10 col-sm-9 sidebar-right">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1>Job Posting Admin Panel</h1>
            </div>
            <div class="panel-body">
                <div class="row job-posting-stat-wrapper">
                    <div class="col-sm-4 col-md-2">
                        <div class="job-posting-stat-tile">
                            <h2>Posts</h2>
                            <span class="job-posting-stat">{{ number_format($stats['job_posts']) }}</span>
                            <div class="job-posting-stat-description">Today</div>
                        </div>
                    </div>
                    <div class="col-sm-4 col-md-2">
                        <div class="job-posting-stat-tile">
                            <h2>Posts</h2>
                            <span class="job-posting-stat">{{ number_format($stats['job_posts_7']) }}</span>
                            <div class="job-posting-stat-description">Last 7 Days</div>
                        </div>
                    </div>
                    <div class="col-sm-4 col-md-2">
                        <div class="job-posting-stat-tile">
                            <h2>Views</h2>
                            <span class="job-posting-stat">{{ number_format($stats['job_views']) }}</span>
                            <div class="job-posting-stat-description">Today</div>
                        </div>
                    </div>
                    <div class="col-sm-4 col-md-2">
                        <div class="job-posting-stat-tile">
                            <h2>Views</h2>
                            <span class="job-posting-stat">{{ number_format($stats['job_views_7']) }}</span>
                            <div class="job-posting-stat-description">Last 7 Days</div>
                        </div>
                    </div>
                    <div class="col-sm-4 col-md-2">
                        <div class="job-posting-stat-tile">
                            <h2>Apps</h2>
                            <span class="job-posting-stat">{{ number_format($stats['job_apps']) }}</span>
                            <div class="job-posting-stat-description">Today</div>
                        </div>
                    </div>
                    <div class="col-sm-4 col-md-2">
                        <div class="job-posting-stat-tile">
                            <h2>Apps</h2>
                            <span class="job-posting-stat">{{ number_format($stats['job_apps_7']) }}</span>
                            <div class="job-posting-stat-description">Last 7 Days</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h1>Job Postings</h1>
            </div>
            <div class="panel-body">
                @include('pages.job._table')
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/pages/job/create.blade.php
@extends('layouts.poster')

@section('title', '')
@section('metaDescription', '')
@section('siteBackground', 'home-background-logo')

@section('poster-content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1>Create Job Posting</h1>
        </div>
        <div class="panel-body">
            {!! Form::open(array('route' => 'job.store','method'=>'POST')) !!}
            @include('pages.job._form')
            <div class="row">
                <div class="col-xs-12 text-center">
                    <button type="submit" class="btn btn-primary" tabindex="7">Next</button>
                </div>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/pages/job/edit.blade.php
@extends('layouts.poster')

@section('title', '')
@section('metaDescription', '')
@section('siteBackground', 'home-background-logo')

@section('poster-content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1>Job Posting Edit</h1>
        </div>
        <div class="panel-body">

            {!! Form::model($jobPosting, array('route' => ['job.update', $jobPosting->id ],'method'=>'PATCH')) !!}
            @include('pages.job._form')
            <div class="row">
                <div class="col-xs-12 text-center">
                    <button type="submit" class="btn btn-primary" tabindex="7">Update</button>
                    <a href="{{ route('job.requirement.edit',$jobPosting->id) }}"><button type="button" class="btn btn-primary" tabindex="8">Edit Requirements</button></a>
                </div>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/pages/job/index.blade.php
@extends('layouts.poster')

@section('title', '')
@section('metaDescription', '')
@section('siteBackground', 'home-background-logo')

@section('poster-content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-8">
                    <h1>Job Posting</h1>
                </div>
                <div class="col-xs-4">
                    <div class="pull-right">
                        @if(! $jobPostings->lastPage() && $jobPostings->currentPage() != 1)
                        {{ ( $jobPostings->currentPage() * $jobPostings->perPage()) - $jobPostings->perPage() + 1 }} -
                        {{  $jobPostings->currentPage() * $jobPostings->perPage() }} of {{ $jobPostings->total() }}
                        @else
                            {{ ( $jobPostings->currentPage() * $jobPostings->perPage()) - $jobPostings->perPage() + 1 }} -
                            {{  $jobPostings->currentPage() * $jobPostings->perPage() - $jobPostings->perPage() + $jobPostings->count() }}
                            of {{ $jobPostings->total() }}
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-body">

        @include('pages.job._table')

        </div>
    </div>
@endsection

resources/views/pages/job/show.blade.php
@extends('layouts.poster')

@section('title', '')
@section('metaDescription', '')
@section('siteBackground', 'home-background-logo')

@section('poster-content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1>Job Details</h1>
        </div>
        <div class="panel-body">
            <div class="row">
                <div  class="col-md-10 col-md-offset-1">
                    <h1 class="job-posting-company">{{ $jobPosting->company }}</h1>
                    <h2 class="job-posting-position">{{ $jobPosting->position }} - {{ $jobPosting->location_city . ", " . $jobPosting->location_state }}</h2>
                    <div class="job-posting-description">
                        {!! $jobPosting->description !!}
                    </div>

                    @if(count($jobPosting->jobPostingExperienceReq) > 0 )
                        <div class="job-posting-requirement">
                            <h4><strong>Required Experience</strong></h4>
                            <ul>
                                @foreach($jobPosting->jobPostingExperienceReq as $expReq)
                                    <li>{{ $expReq->experience }} - {{ $expReq->years }} yr</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif


                    @if(count($jobPosting->jobPostingLanguageReq) > 0)
                        <div class="job-posting-requirement">
                            <h4><strong>Required Languages</strong></h4>
                            <ul>
                                @foreach($jobPosting->jobPostingLanguageReq as $langReq)
                                    <li>{{ $langReq->language }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif


                    @if(count($jobPosting->jobPostingLicenseReq) > 0)
                        <div class="job-posting-requirement">
                            <h4><strong>Required Licenses</strong></h4>
                            <ul>
                                @foreach($jobPosting->jobPostingLicenseReq as $licReq)
                                    <li>{{ $licReq->license }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="application text-center">
                        <button id="job-application-btn" class="btn btn-primary" data-id="{{ $jobPosting->id }}">Apply</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@include('partials.modal.confirmJobApplication')